# -*- coding: utf-8 -*-
"""py_libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FauEqU4XpggeB04Jyl8NXvZKZ33WhkSZ
"""

!pip install -q git+https://github.com/ziatdinovmax/pyroved.git

import os
import math
import numpy as np
import seaborn as sns
import pandas as pd
import time
import random

import torch

from torch.nn import Conv1d, ConvTranspose1d
from torch.nn import Linear as Lin, ReLU, Sigmoid, ConstantPad1d
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import StratifiedKFold

from matplotlib import pyplot as plt
from tqdm import tqdm

import pyroved as pv
import torch
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')