# -*- coding: utf-8 -*-
"""train_vae.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pCu36OBqrrtDzYAoNRJbX4awQZDP4-H
"""

channel_0 = (140081, )

# Initialize vanilla VAE
# Change to latent_dim = 3 for 3D latent space
vae = pv.models.iVAE(data_dim = (400,), latent_dim = 2, invariances=None, seed=0)

# Initialize trainer
trainer = pv.trainers.SVItrainer(vae)

# Train for n epochs:
for e in range(55):
    trainer.step(train_loader_0)
    trainer.print_statistics()

# CHANNEL 0 Latent Manifold
vae.manifold2d(d=10)

channel_1 = (140081, )

# Initialize vanilla VAE
# Change to latent_dim = 3 for 3D latent space
vae = pv.models.iVAE(data_dim = (400,), latent_dim = 2, invariances=None, seed=0)

# Initialize trainer
trainer = pv.trainers.SVItrainer(vae)

# Train for n epochs:
for e in range(55):
    trainer.step(train_loader_1)
    trainer.print_statistics()

# CHANNEL 1 Latent Manifold
vae.manifold2d(d = 10)