# -*- coding: utf-8 -*-
"""latent_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xawH4S-ZnmDCnHXbbucv8wZCxYdq3-zI
"""

# 2D, CHANNEL 0, LATENT SPACE

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

z_mean, z_sd = vae.encode(X_train_C0)
fig = plt.figure(figsize=(15, 6), dpi=300)

ax1 = fig.add_subplot(121)
target_names = ["FS", "FSglyc", "CFA", "ATD", "VA", "Fe2O3", "Fe3O4"]
cmap1 = ListedColormap(['red', 'purple', 'yellow', 'gray', 'brown', 'blue', 'green'])

idx_0 = 0
im1 = ax1.scatter(z_mean[:, -1], z_mean[:, -2], s=1, c=Y_train, cmap=cmap1)

ax1.set_xlabel("$z_1$", fontsize=14)
ax1.set_ylabel("$z_2$", fontsize=14)
cbar1 = fig.colorbar(im1, ax=ax1, ticks=range(len(cmap1.colors)), shrink=.8)
cbar1.set_ticklabels(target_names)
cbar1.set_label("$\mu$", fontsize=14)

plt.savefig('new_2D_Chart.png', dpi=300)
plt.show()

# HIGH Resolution Download
# from google.colab import files
# files.download('new_2D_Chart.png')

#3D, CHANNEL 0, LATENT SPACE

from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt

z_mean, z_sd = vae.encode(X_train_C0)
fig = plt.figure(figsize=(15, 6), dpi=300)
ax1 = fig.add_subplot(121, projection='3d')
target_names = ["FS", "FSglyc", "CFA", "ATD", "VA", "Fe2O3", "Fe3O4"]

cmap1 = ListedColormap(['red', 'purple', 'yellow', 'gray', 'brown', 'blue', 'green'])
im1 = ax1.scatter(z_mean[:, -1], z_mean[:, -2], z_mean[:, -3], s=1, c=Y_train, cmap=cmap1)
ax1.set_xlabel("$z_1$", fontsize=14)
ax1.set_ylabel("$z_2$", fontsize=14)
ax1.set_zlabel("$z_3$", fontsize=14)
cbar1 = fig.colorbar(im1, ax=ax1, ticks=range(len(cmap1.colors)), shrink=0.8)
cbar1.set_ticklabels(target_names)
cbar1.set_label("$\mu$", fontsize=14)

plt.savefig('3D_scatter_plots.png', dpi=300)
plt.show()
# HIGH Resolution Download
# from google.colab import files
# files.download('3D_scatter_plots.png')

# CHANNEL 0, 2D, Individual Classes

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import numpy as np
from google.colab import files

z_mean, z_sd = vae.encode(X_train_C0)

target_names = ["FS", "FSglyc", "CFA", "ATD", "VA", "Fe2O3", "Fe3O4"]
cmap1 = ListedColormap(['red', 'purple', 'yellow', 'gray', 'brown', 'blue', 'green'])


fig, axs = plt.subplots(2, 4, figsize=(20, 10))

for idx_0 in range(7):
    class_indices = np.where(Y_train == idx_0)
    z_mean_class = z_mean[class_indices]


    ax = axs[idx_0 // 4, idx_0 % 4]
    ax.scatter(z_mean_class[:, -1], z_mean_class[:, -2], s=1, color=cmap1(idx_0), label=target_names[idx_0])
    ax.set_xlabel("$z_1$", fontsize=14)
    ax.set_ylabel("$z_2$", fontsize=14)
    ax.legend()
    ax.set_title(target_names[idx_0])


ax_all = axs[1, 3]
for idx_0 in range(7):
    class_indices = np.where(Y_train == idx_0)
    z_mean_class = z_mean[class_indices]
    ax_all.scatter(z_mean_class[:, -1], z_mean_class[:, -2], s=1, color=cmap1(idx_0), label=target_names[idx_0])

ax_all.set_xlabel("$z_1$", fontsize=14)
ax_all.set_ylabel("$z_2$", fontsize=14)
ax_all.legend()
ax_all.set_title("All Classes")

plt.tight_layout()
filename = 'individualAerosolClass.png'
plt.savefig(filename, dpi=300)
plt.show()

# HIGH Resolution Download
# files.download(filename)

#CHANNEL 0, 3D, Individual Classes

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import ListedColormap
import numpy as np
from google.colab import files

z_mean, z_sd = vae.encode(X_train_C0)

target_names = ["FS", "FSglyc", "CFA", "ATD", "VA", "Fe2O3", "Fe3O4"]
cmap1 = ListedColormap(['red', 'purple', 'yellow', 'gray', 'brown', 'blue', 'green'])

fig, axs = plt.subplots(2, 4, figsize=(20, 10), subplot_kw={'projection': '3d'})

for idx_0 in range(7):
    class_indices = np.where(Y_train == idx_0)[0]  # Ensure proper indexing
    z_mean_class = z_mean[class_indices]

    ax = axs[idx_0 // 4, idx_0 % 4]
    ax.scatter(z_mean_class[:, -1], z_mean_class[:, -2], z_mean_class[:, -3], s=1, color=cmap1(idx_0), label=target_names[idx_0])
    ax.set_xlabel("$z_1$", fontsize=14)
    ax.set_ylabel("$z_2$", fontsize=14)
    ax.set_zlabel("$z_3$", fontsize=14)
    ax.legend()
    ax.set_title(target_names[idx_0])

ax_all = axs[1, 3]
for idx_0 in range(7):
    class_indices = np.where(Y_train == idx_0)[0]
    z_mean_class = z_mean[class_indices]
    ax_all.scatter(z_mean_class[:, -1], z_mean_class[:, -2], z_mean_class[:, -3], s=1, color=cmap1(idx_0), label=target_names[idx_0])

ax_all.set_xlabel("$z_1$", fontsize=14)
ax_all.set_ylabel("$z_2$", fontsize=14)
ax_all.set_zlabel("$z_3$", fontsize=14)
ax_all.legend()
ax_all.set_title("All Classes")

plt.tight_layout()
filename = '3D_individualAerosolClass.png'
plt.savefig(filename, dpi=300)
plt.show()

# HIGH Resolution Download
# files.download(filename)

# 2D, CHANNEL 1, LATENT SPACE

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

z_mean_1, z_sd_1 = vae.encode(X_train_C1)
fig = plt.figure(figsize=(15, 6), dpi=300)

ax1 = fig.add_subplot(121)
target_names = ["FS", "FSglyc", "CFA", "ATD", "VA", "Fe2O3", "Fe3O4"]
cmap1 = ListedColormap(['red', 'purple', 'yellow', 'gray', 'brown', 'blue', 'green'])
im1 = ax1.scatter(z_mean_1[:, -1], z_mean_1[:, -2], s=1, c=Y_train, cmap=cmap1)
ax1.set_xlabel("$z_1$", fontsize=14)
ax1.set_ylabel("$z_2$", fontsize=14)
cbar1 = fig.colorbar(im1, ax=ax1, ticks=range(len(cmap1.colors)), shrink=.8)
cbar1.set_ticklabels(target_names)
cbar1.set_label("$\mu$", fontsize=14)

plt.savefig('high_res_scatter_plot_channel_1.png', dpi=300)
plt.show()

# HIGH Resolution Download
# from google.colab import files
# files.download('high_res_scatter_plot_channel_1.png')

# 3D, CHANNEL 1, LATENT SPACE

from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt

z_mean_1, z_sd_1 = vae.encode(X_train_C1)
fig = plt.figure(figsize=(26, 8), dpi=300)
ax1 = fig.add_subplot(121, projection='3d')
target_names = ["FS", "FSglyc", "CFA", "ATD", "VA", "Fe2O3", "Fe3O4"]

cmap1 = ListedColormap(['red', 'purple', 'yellow', 'gray', 'brown', 'blue', 'green'])
im1 = ax1.scatter(z_mean_1[:, -1], z_mean_1[:, -2], z_mean_1[:, -3], s=1, c=Y_train, cmap=cmap1)
ax1.set_xlabel("$z_1$", fontsize=14)
ax1.set_ylabel("$z_2$", fontsize=14)
ax1.set_zlabel("$z_3$", fontsize=14)
cbar1 = fig.colorbar(im1, ax=ax1, ticks=range(len(cmap1.colors)), shrink=0.8)
cbar1.set_ticklabels(target_names)
cbar1.set_label("$\mu$", fontsize=14)

plt.savefig('3D_scatter_plots_c1.png', dpi=300)
plt.show()

# HIGH Resolution Download
# from google.colab import files
# files.download('3D_scatter_plots_c1.png')

# CHANNEL 1, 2D, Individual Classes
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import numpy as np
from google.colab import files

z_mean_1, z_sd_1 = vae.encode(X_train_C1)

target_names = ["FS", "FSglyc", "CFA", "ATD", "VA", "Fe2O3", "Fe3O4"]
cmap1 = ListedColormap(['red', 'purple', 'yellow', 'gray', 'brown', 'blue', 'green'])

fig, axs = plt.subplots(2, 4, figsize=(20, 10))

for idx_1 in range(7):
    class_indices = np.where(Y_train == idx_1)
    z_mean_class = z_mean_1[class_indices]

    ax = axs[idx_1 // 4, idx_1 % 4]
    ax.scatter(z_mean_class[:, -1], z_mean_class[:, -2], s=1, color=cmap1(idx_1), label=target_names[idx_1])
    ax.set_xlabel("$z_1$", fontsize=14)
    ax.set_ylabel("$z_2$", fontsize=14)
    ax.legend()
    ax.set_title(target_names[idx_1])

ax_all = axs[1, 3]
for idx_1 in range(7):
    class_indices = np.where(Y_train == idx_1)
    z_mean_class = z_mean_1[class_indices]
    ax_all.scatter(z_mean_class[:, -1], z_mean_class[:, -2], s=1, color=cmap1(idx_1), label=target_names[idx_1])

ax_all.set_xlabel("$z_1$", fontsize=14)
ax_all.set_ylabel("$z_2$", fontsize=14)
ax_all.legend()
ax_all.set_title("All Classes")

plt.tight_layout()
filename = 'individualAerosolClass_1.png'
plt.savefig(filename, dpi=300)
plt.show()

# HIGH Resolution Download
# files.download(filename)

# CHANNEL 1, 3D, Individual Classes
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import ListedColormap
import numpy as np
from google.colab import files

z_mean_1, z_sd_1 = vae.encode(X_train_C1)

target_names = ["FS", "FSglyc", "CFA", "ATD", "VA", "Fe2O3", "Fe3O4"]
cmap1 = ListedColormap(['red', 'purple', 'yellow', 'gray', 'brown', 'blue', 'green'])

fig, axs = plt.subplots(2, 4, figsize=(20, 10), subplot_kw={'projection': '3d'})

for idx_1 in range(7):
    class_indices = np.where(Y_train == idx_1)[0]
    z_mean_class = z_mean_1[class_indices]

    ax = axs[idx_1 // 4, idx_1 % 4]
    ax.scatter(z_mean_class[:, -1], z_mean_class[:, -2], z_mean_class[:, -3], s=1, color=cmap1(idx_1), label=target_names[idx_1])
    ax.set_xlabel("$z_1$", fontsize=14)
    ax.set_ylabel("$z_2$", fontsize=14)
    ax.set_zlabel("$z_3$", fontsize=14)
    ax.legend()
    ax.set_title(target_names[idx_0])

ax_all = axs[1, 3]
for idx_1 in range(7):
    class_indices = np.where(Y_train == idx_1)[0]
    z_mean_class = z_mean_1[class_indices]
    ax_all.scatter(z_mean_class[:, -1], z_mean_class[:, -2], z_mean_class[:, -3], s=1, color=cmap1(idx_1), label=target_names[idx_1])

ax_all.set_xlabel("$z_1$", fontsize=14)
ax_all.set_ylabel("$z_2$", fontsize=14)
ax_all.set_zlabel("$z_3$", fontsize=14)
ax_all.legend()
ax_all.set_title("All Classes")

plt.tight_layout()
filename = '3D_individualAerosolClass_channel_1.png'
plt.savefig(filename, dpi=300)
plt.show()

# HIGH Resolution Download
# files.download(filename)