# -*- coding: utf-8 -*-
"""rf_verify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaV0lk5O0dhGAuy-OFBvcddwJB6zoZ7r
"""

from sklearn.model_selection import train_test_split
X_train_rf, X_test_rf, y_train_rf, y_test_rf = train_test_split(X_scaled, Y_filtered, test_size=0.33, random_state=42)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_rf, y_train_rf)

y_output = rf.predict(X_test_rf)

# CONFUSION Matrix for Random Forest Algorithmn
# Illustrates the feasibility of Unsupervised Approach

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files

correlation_arr = confusion_matrix(y_output, y_test_rf, normalize='true')

plt.figure(figsize=(10, 8), dpi=300)
ax = sns.heatmap(correlation_arr, annot=True, fmt=".2%", cmap='viridis')
ax.set_title('Confusion Matrix with Normalized Percentages')
ax.set_ylabel('Predicted Label')
ax.set_xlabel('True Label')

plt.savefig('confusion_matrix_high_res.png', dpi=300)
plt.show()
# HIGH Resolution Download
# files.download('confusion_matrix_high_res.png')